# Generated by Django 3.2.5 on 2021-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=255)),
                ('empquality', models.CharField(max_length=255)),
                ('empcomposition', models.CharField(max_length=255)),
            ],
        ),
    ]
